# Generated by Django 4.2.3 on 2023-07-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_bot_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='openai_api_key',
            field=models.CharField(default='ajay', max_length=255),
        ),
        migrations.AlterField(
            model_name='bot',
            name='organization',
            field=models.CharField(max_length=25),
        ),
    ]
